config/routes.rb
Rails.application.routes.draw do
  
  get 'purchase/index'
  get 'purchase/done'
  get 'credit_cards/new'
  get 'credit_cards/show'
  post   '/like/:item_id' => 'likes#like',   as: 'like'
  delete '/like/:item_id' => 'likes#unlike', as: 'unlike'
  

  devise_for :users

    devise_scope :user do
      get 'uses/before_sign_up' => 'devise/registrations#before_signup', as: :before_signup_user_registration
      post 'uses/before_sign_up(.:format)' => 'devise/registrations#before_signup'
      post 'users/sign_up' => 'users/registrations#new'
      get 'users/new2' => 'devise/registrations#new2', as: :new2_user_registration
      post 'users/new2(.:format)' => 'devise/registrations#new2'
      get 'users/new3' => 'devise/registrations#new3', as: :new3_user_registration
      post 'users/new3(.:format)' => 'devise/registrations#new3'
      get 'users/new4' => 'devise/registrations#new4', as: :new4_user_registration
      post 'users/new4(.:format)' => 'devise/registrations#new4'
      get 'users/new5' => 'devise/registrations#new5', as: :new5_user_registration
      post 'users/new5(.:format)' => 'devise/registrations#new5'      
    end

  root to: 'items#index'
  get 'mypages' => 'mypages#index'
  get 'itemsshow' => 'items#show'
  get 'users/logout' => 'users#logout'
  get 'users/credit' => 'users#credit'
  get 'itemscheck' => 'items#check'
  get 'itemsindex' => 'items#index'
  

  resources :mypages, only: [:index,:edit]do
    collection do
      get "credit", to: "mypages#credit"
      get "logout", to: "mypages#logout"
      get "profile", to: "mypages#profile"
      get "identification", to: "mypages#identification"
      get "myitem", to: "mypages#myitem"
    end
    member do
      get 'item', to: 'mypages#item'
      post 'stop', to: 'mypages#stop'
      post 'start', to: 'mypages#start'
    end
    
  end

  resources :items, only: [:index, :show, :new, :destroy, :edit, :create] do
    collection do
      get "check/:id(.:format)", to: "items#check"
      get 'child_category'
      get 'grandchild_category'
      get 'size'
      get 'search'
    end
  end

  resources :credit_cards, only: [:new, :show] do
    collection do
      post  'new', to: 'credit_cards#new'
      post 'show', to: 'credit_cards#show'
      post 'pay', to: 'credit_cards#pay'
    end
  end
  resources :purchase, only: [:index] do
    collection do
      get 'index', to: 'purchase#index'
      get 'done/:id(.:format)', to: 'purchase#done'
    end
    member do
      post 'pay', to: 'purchase#pay'
    end
  end
 
  resources :signups do
    collection do
      get :registration
      post :registration
      get :phone
      get :address
      get :credit
      get :done
    end
  end
  
  resources :users
  resources :category do
  end  
end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
  before_action :validates_registration, only: :phone
  before_action :validates_address, only: :create
  
  require "payjp"

  def registration
    @user = User.new
    @user.build_personal_information
  end

  def phone
    @user = User.new
    @user.build_personal_information
    user_params[:personal_information_attributes][:birth] = birthday
    session[:birth] = birthday
    session[:dummylongcode] = "1111111"
    session[:dummyshortcode] = "10"
    params[:user][:personal_information_attributes][:postal_code] = session[:dummylongcode]
    params[:user][:personal_information_attributes][:prefecture_id] = session[:dummyshortcode]
    params[:user][:personal_information_attributes][:city] = session[:dummyshortcode]
    params[:user][:personal_information_attributes][:address] = session[:dummyshortcode]
    session[:nickname] = user_params[:nickname]
    session[:email] = user_params[:email]
    session[:password] = user_params[:password]
    session[:password_confirmation] = user_params[:password_confirmation]
    session[:personal_information_attributes] = user_params[:personal_information_attributes]
    @user = User.new(
      nickname: session[:nickname],
      email: session[:email],
      password: session[:password],
      password_confirmation: session[:password_confirmation]
    )
    @user.build_personal_information(session[:personal_information_attributes])

  end
  
  def address
    @user = User.new
    @user.build_personal_information
  end



  def create
    @user = User.new(
      nickname: session[:nickname],
      email: session[:email],
      password: session[:password],
      password_confirmation: session[:password_confirmation]
    )
    @user.build_personal_information
    params[:user][:personal_information_attributes][:last_name] = session[:last_name]
    params[:user][:personal_information_attributes][:first_name] = session[:first_name] 
    params[:user][:personal_information_attributes][:last_name_kana] = session[:last_name_kana]
    params[:user][:personal_information_attributes][:first_name_kana] = session[:first_name_kana]
    params[:user][:personal_information_attributes][:birth] = session[:birth]
    session[:personal_information_attributes] = user_params[:personal_information_attributes]
    @user.build_personal_information(session[:personal_information_attributes])
    if @user.save
      session[:id] = @user.id
      UserEvaluation.create(
        user_id: @user.id,
        good: 0,
        normal: 0,
        bad: 0
      )
      sign_in User.find(session[:id]) unless user_signed_in?
      redirect_to credit_signups_path
    else
      render "/signups/address"
    end
  end

  def credit
    
    gon.payjp_api_key = ENV['PAYJP_ACCESS_KEY']
    gon.publickey = ENV['PAYJP_PUBLIC_KEY']
    @credit_card = CreditCard.where(user_id: current_user.id)
    redirect_to root_path if @credit_card.exists?

  end

  def new
    gon.payjp_api_key = ENV['PAYJP_ACCESS_KEY']
    gon.publickey = ENV['PAYJP_PUBLIC_KEY']
    @credit_card = CreditCard.where(user_id: current_user.id)
    redirect_to root_path if @credit_card.exists?
  end

  def pay
    Payjp.api_key = ENV["PAYJP_ACCESS_KEY"]
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(card: params['payjp-token'])
      @credit_card = CreditCard.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @credit_card.save
        redirect_to root_path
      else
        redirect_to action: "pay"
      end
    end
  end

  def show 
    @credit_card = CreditCard.where(user_id: current_user.id).first
    if @credit_card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = ENV["PAYJP_ACCESS_KEY"]
      customer = Payjp::Customer.retrieve(@credit_card.customer_id)
      @default_card_information = customer.cards.retrieve(@credit_card.card_id)
    end
  end

  def done
    # sign_in User.find(session[:id]) unless user_signed_in?
  end

  private
  def user_params
    params.require(:user).permit(:nickname,:email,:password, :password_confirmation, 
    personal_information_attributes:[:id, :user_id, :first_name, :last_name, :first_name_kana, :last_name_kana, :birth, :postal_code, :prefecture_id, :city, :address, :building_name, :phone_number])
  end

  def birthday
    date = user_params[:personal_information_attributes]
    date["birth(1i)"].to_s + "-" + date["birth(2i)"].to_s + "-" + date["birth(3i)"].to_s
    if date["birth(1i)"].empty? && date["birth(2i)"].empty? && date["birth(3i)"].empty?
      return
    end
    return date["birth(1i)"].to_s + "-" + date["birth(2i)"].to_s + "-" + date["birth(3i)"].to_s
  end

  def validates_registration
    session[:dummylongcode] = "1111111"
    session[:dummyshortcode] = "10"
    params[:user][:personal_information_attributes][:postal_code] = session[:dummylongcode]
    params[:user][:personal_information_attributes][:prefecture_id] = session[:dummyshortcode]
    params[:user][:personal_information_attributes][:city] = session[:dummyshortcode]
    params[:user][:personal_information_attributes][:address] = session[:dummyshortcode]
    session[:last_name] = user_params[:personal_information_attributes][:last_name]
    session[:first_name] = user_params[:personal_information_attributes][:first_name]
    session[:last_name_kana] = user_params[:personal_information_attributes][:last_name_kana]
    session[:first_name_kana] = user_params[:personal_information_attributes][:first_name_kana]
    session[:nickname] = user_params[:nickname]
    session[:email] = user_params[:email]
    session[:password] = user_params[:password]
    session[:password_confirmation] = user_params[:password_confirmation]
    session[:personal_information_attributes] = user_params[:personal_information_attributes]
    @user = User.new(
      nickname: session[:nickname],
      email: session[:email],
      password: session[:password],
      password_confirmation: session[:password_confirmation]
    )
    @user.build_personal_information(session[:personal_information_attributes])
    @user.valid?
    if @user.errors.any?
      @error = @user.errors.full_messages_for(:base)
        render registration_signups_path
    end
  end

  def validates_address
    @user = User.new(
      nickname: session[:nickname],
      email: session[:email],
      password: session[:password],
      password_confirmation: session[:password_confirmation]
    )
    @user.build_personal_information
    params[:user][:personal_information_attributes][:last_name] = session[:last_name]
    params[:user][:personal_information_attributes][:first_name] = session[:first_name] 
    params[:user][:personal_information_attributes][:last_name_kana] = session[:last_name_kana]
    params[:user][:personal_information_attributes][:first_name_kana] = session[:first_name_kana]
    params[:user][:personal_information_attributes][:birth] = session[:birth]
    session[:personal_information_attributes] = user_params[:personal_information_attributes]
    @user.build_personal_information(session[:personal_information_attributes])
    render address_signups_path unless @user.valid?
  end

end

app/helpers/signup_helper.rb
module SignupHelper
end

app/views/signups/_errors.html.haml
- if table.errors.any?
  - if errors = table.errors.full_messages_for(column.to_sym)
    %ul.errors-text
      - errors.each do |error|
        %li=error        

app/views/signups/_signups_credit_cards.html.haml
.cards-contents
  .cards-contents__detail
    = form_tag(pay_credit_cards_path, method: :post, id: 'charge-form',  name: "inputForm") do
      .cards-contents__detail-contet
        .cards-contents__detail-contet-number
          %label.payment-card-no カード番号
          %span.form-reqire 必須
          = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
          %ul.card-logo
            %li
              = image_tag "visa.svg", size:"49x20", class: "card-logo-img"
            %li
              = image_tag "master_card.svg", size:"34x20", class: "card-logo-img"
            %li
              = image_tag "saison-card.svg", size:"30x20", class: "card-logo-img"
            %li
              = image_tag "jcb.svg", size:"32x20", class: "card-logo-img"
            %li
              = image_tag "american_express.svg", size:"21x20", class: "card-logo-img"
            %li
              = image_tag "dinersclub.svg", size:"32x20", class: "card-logo-img"
            %li
              = image_tag "discover.svg", size:"32x20", class: "card-logo-img"
        .cards-contents__detail-contet-limit
          %label.payment-card-expire 有効期限
          %span.form-reqire 必須
          %br
          %select#exp_month{name: "exp_month", class: "exp_month", type: "text"}
            %option{value: ""} --
            %option{value: "1"}01
            %option{value: "2"}02
            %option{value: "3"}03
            %option{value: "4"}04
            %option{value: "5"}05
            %option{value: "6"}06
            %option{value: "7"}07
            %option{value: "8"}08
            %option{value: "9"}09
            %option{value: "10"}10
            %option{value: "11"}11
            %option{value: "12"}12
            -# = fa_icon "chevron-down", class:"arrow-down-icon"
          %span 月
          %select#exp_year{name: "exp_year", class: "exp_year", type: "text"}
            %option{value: ""} --
            %option{value: "2019"}19
            %option{value: "2020"}20
            %option{value: "2021"}21
            %option{value: "2022"}22
            %option{value: "2023"}23
            %option{value: "2024"}24
            %option{value: "2025"}25
            %option{value: "2026"}26
            %option{value: "2027"}27
            %option{value: "2028"}28
            %option{value: "2029"}29
          %span 年
        .cards-contents__detail-contet-cvc
          %label.card_security_code セキュリティコード
          %span.form-reqire 必須
          = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面4桁もしくは3桁の番号", maxlength: "4", id: "cvc"
        .cards-contents__detail-contet-btn
          .signup-seqcode-text
            %span.form-question ?
            カード裏面の番号とは？

          .submit-btn
            #card_token
            %button#token_submit{type: "button"} 次へ
            = link_to "登録しないならこちら", done_signups_path

        

app/views/signups/address.html.haml
.wrapper
  .signup__header
    .signup__header__mercari-logo
      = link_to image_tag("logo.svg"), root_path
    .signup__header__progress
      %ul.progress
        %li.through
          会員情報
          .bubble.bubble-first
        %li.through
          電話番号認証
          .bubble
        %li.active
          お届け先住所入力
          .bubble
        %li
          支払い方法
          .bubble
        %li
          完了
          .bubble.bubble-last
  .signup__panel
    .signup__panel__title
      %h2 住所入力
    = form_with model: @user, url: signups_path, method: :post, local: true do |form|
      = form.fields_for :personal_information, @user.personal_information do |i|
        .signup__panel__field.signup__panel__field
          .field
            = i.label :郵便番号
            %span.required 必須
            %br/
            = i.text_field :postal_code, placeholder: "例）123-4567"
            = render partial: "shared/signups/errors", locals: {table: @user.personal_information, column: "postal_code"}
            %br/
          .field
            %label 都道府県
            %span.required 必須
            %br/
            = i.collection_select :prefecture_id, Prefecture.all, :id, :name
            %br/
            %br/
            = render partial: "shared/signups/errors", locals: {table: @user.personal_information, column: "prefecture_id"}
            %br/
          .field
            %br/
            %label 市区町村
            %span.required 必須
            %br/
            = i.text_field :city, placeholder: "例）横浜市緑区"
            = render partial: "shared/signups/errors", locals: {table: @user.personal_information, column: "city"}
            %br/
          .field
            %label 番地
            %span.required 必須
            %br/
            = i.text_field :address, placeholder: "例）青山1-1-1"
            = render partial: "shared/signups/errors", locals: {table: @user.personal_information, column: "address"}
            %br/
          .field
            %label 建物名
            %span.optional 任意
            %br/
            = i.text_field :building_name, placeholder: "例）柳ビル103"
            %br/
          .field
            %label 電話番号
            %span.optional 任意
            %br/
            = i.text_field :phone_number, placeholder: "例）09012345678"
            %br/
          .actions
            = form.submit "次に進む", class: "btn action-btn"
    = render "devise/shared/footer"

app/views/signups/credit.html.haml
.signin
  .signup__header
    .signup__header__mercari-logo
      = link_to image_tag("logo.svg"), root_path
    .signup__header__progress
      %ul.progress
        %li.through
          会員情報
          .bubble.bubble-first
        %li.through
          電話番号認証
          .bubble
        %li.through
          お届け先住所入力
          .bubble
        %li.active
          支払い方法
          .bubble
        %li
          完了
          .bubble.bubble-last
  .signup__panel
    .signup__panel__title
      %h2 支払い方法
    .my-container2
      = render "signups/signups_credit_cards"

      .actions
        -# = form.submit "次に進む", class: "btn action-btn"
  
  

app/views/signups/done.html.haml
.signin
  .signup__header
    .signup__header__mercari-logo
      = link_to image_tag("logo.svg"), root_path
    .signup__header__progress
      %ul.progress
        %li.through
          会員情報
          .bubble.bubble-first
        %li.through
          電話番号認証
          .bubble
        %li.through
          お届け先住所入力
          .bubble
        %li.through
          支払い方法
          .bubble
        %li.active
          完了
          .bubble.bubble-last
  .signup__panel
    .signup__panel__title
      %h2 会員登録完了
    .signup__panel__field.last__field
      %p ありがとうございます。
      %p 会員登録が完了しました。
      %br/
      .actions
        = button_to "メルカリを始める", root_path, method: :get, class: "btn action-btn"
  = render "devise/shared/footer"

app/views/signups/phone.html.haml
.wrapper
  .signup__header
    .signup__header__mercari-logo
      = link_to image_tag("logo.svg"), root_path
    .signup__header__progress
      %ul.progress
        %li.through
          会員情報
          .bubble.bubble-first
        %li.active
          電話番号認証
          .bubble
        %li
          お届け先住所入力
          .bubble
        %li
          支払い方法
          .bubble
        %li
          完了
          .bubble.bubble-last
  .signup__panel
    .signup__panel__title
      %h2 電話番号の確認
    = form_with model: @user, url: address_signups_path, method: :get, local: true do |form|
      = form.fields_for :personal_information, @user.personal_information do |i|
        .signup__panel__field
          .field
            %label 携帯電話の番号
            %br/
            = i.text_field :phone_number, placeholder: "携帯電話の番号を入力"
            = render partial: "shared/signups/errors", locals: {table: @user.personal_information, column: "phone_number"}
            %p 本人確認のため、携帯電話のSMS(ショートメッセージサービス)を利用して認証を行います。
            %br/
            %br/
          .actions
            = form.submit "SMSを送信する", class: "btn action-btn"
            %br/
          .field
            %p ※電話番号は本人確認や不正利用防止のために利用します。他のユーザーに公開されることはありません。
          .field
            .field__right
              = link_to user_session, class: "terms__link" do
                電話番号の確認が必要な理由
                %span.angle-right
                  = fa_icon "angle-right"
  = render "devise/shared/footer"

app/views/signups/registration.html.haml
.wrapper
.signup__header
  .signup__header__mercari-logo
    = link_to image_tag("logo.svg"), root_path
  .signup__header__progress
    %ul.progress
      %li.active
        会員情報
        .bubble.bubble-first
      %li
        電話番号認証
        .bubble
      %li
        お届け先住所入力
        .bubble
      %li
        支払い方法
        .bubble
      %li
        完了
        .bubble.bubble-last
.signup__panel
  .signup__panel__title
    %h2 会員情報入力  
  = form_with model: @user, url: phone_signups_path, method: :get, local: true do |form|
    .signup__panel__field
      .field
        = form.label :ニックネーム
        %span.required 必須
        %br/
        = form.text_field :nickname, placeholder: "例）メルカリ太郎"
        = render partial: "errors", locals: {table: @user, column: "nickname"}
        %br/
      .field
        = form.label :メールアドレス
        %span.required 必須
        %br/
        = form.email_field :email, autofocus: true, autocomplete: "email", placeholder: "PC・携帯どちらでも可"
        = render partial: "shared/signups/errors", locals: {table: @user, column: "email"}
      .field
        = form.label :パスワード
        %span.required 必須
        %br/
        = form.password_field :password, autocomplete: "new-password", placeholder: "7文字以上"
        = render partial: "shared/signups/errors", locals: {table: @user, column: "password"}
      .field
        = form.label :パスワード（確認）
        %span.required 必須
        %br/
        = form.password_field :password_confirmation, autocomplete: "new-password", placeholder: "7文字以上"
        = render partial: "shared/signups/errors", locals: {table: @user, column: "password_confirmation"}
      .field
        %h3 本人確認
        %p 安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。
        %br/
      = form.fields_for :personal_information, @user.personal_information do |i|
        .namefield
          = i.label :お名前（全角）
          %span.required 必須
          %br/
          = i.text_field :last_name, placeholder: "例）山田"
          = i.text_field :first_name, placeholder: "例）彩"
        

          = render partial: "shared/signups/errors", locals: {table: @user.personal_information, column: "last_name"}
          = render partial: "shared/signups/errors", locals: {table: @user.personal_information, column: "first_name"}
          %br/
        .namefield
          = i.label :お名前カナ（全角）
          %span.required 必須
          %br/
          = i.text_field :last_name_kana, placeholder: "例）ヤマダ"
          = i.text_field :first_name_kana, placeholder: "例）アヤ"
          = render partial: "shared/signups/errors", locals: {table: @user.personal_information, column: "last_name_kana"}
          = render partial: "shared/signups/errors", locals: {table: @user.personal_information, column: "first_name_kana"}
          %br/
        .field
          = i.label :生年月日
          %span.required 必須
          %br/
          .birth-field
            != sprintf(i.date_select(:birth, prompt:"--",use_month_numbers:true, start_year:Time.now.year, end_year:1900, date_separator:'%s'),'年','月')+'日'
            = render partial: "shared/signups/errors", locals: {table: @user.personal_information, column: "birth"}
            %br/   
        %p.field--text ※本人情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。
        
        %p.field.field__terms
          「次へ進む」のボタンを押すことにより、
          = link_to "利用規約", user_session, class: "terms__link"
          に同意したものとみなします
          %br/
          %br/
      .actions
        = form.submit "次に進む", class: "btn action-btn"
      .field
        .field__right
          = link_to root_path, class: "terms__link" do
            本人情報の登録について
            %span.angle-right
              = fa_icon "angle-right"
  = render "devise/shared/footer"