config/routes.rb
Rails.application.routes.draw do
  
  get 'purchase/index'
  get 'purchase/done'
  get 'credit_cards/new'
  get 'credit_cards/show'
  post   '/like/:item_id' => 'likes#like',   as: 'like'
  delete '/like/:item_id' => 'likes#unlike', as: 'unlike'
  

  devise_for :users

    devise_scope :user do
      get 'uses/before_sign_up' => 'devise/registrations#before_signup', as: :before_signup_user_registration
      post 'uses/before_sign_up(.:format)' => 'devise/registrations#before_signup'
      post 'users/sign_up' => 'users/registrations#new'
      get 'users/new2' => 'devise/registrations#new2', as: :new2_user_registration
      post 'users/new2(.:format)' => 'devise/registrations#new2'
      get 'users/new3' => 'devise/registrations#new3', as: :new3_user_registration
      post 'users/new3(.:format)' => 'devise/registrations#new3'
      get 'users/new4' => 'devise/registrations#new4', as: :new4_user_registration
      post 'users/new4(.:format)' => 'devise/registrations#new4'
      get 'users/new5' => 'devise/registrations#new5', as: :new5_user_registration
      post 'users/new5(.:format)' => 'devise/registrations#new5'      
    end

  root to: 'items#index'
  get 'mypages' => 'mypages#index'
  get 'itemsshow' => 'items#show'
  get 'users/logout' => 'users#logout'
  get 'users/credit' => 'users#credit'
  get 'itemscheck' => 'items#check'
  get 'itemsindex' => 'items#index'
  

  resources :mypages, only: [:index,:edit]do
    collection do
      get "credit", to: "mypages#credit"
      get "logout", to: "mypages#logout"
      get "profile", to: "mypages#profile"
      get "identification", to: "mypages#identification"
      get "myitem", to: "mypages#myitem"
    end
    member do
      get 'item', to: 'mypages#item'
      post 'stop', to: 'mypages#stop'
      post 'start', to: 'mypages#start'
    end
    
  end

  resources :items, only: [:index, :show, :new, :destroy, :edit, :create] do
    collection do
      get "check/:id(.:format)", to: "items#check"
      get 'child_category'
      get 'grandchild_category'
      get 'size'
      get 'search'
    end
  end

  resources :credit_cards, only: [:new, :show] do
    collection do
      post  'new', to: 'credit_cards#new'
      post 'show', to: 'credit_cards#show'
      post 'pay', to: 'credit_cards#pay'
    end
  end
  resources :purchase, only: [:index] do
    collection do
      get 'index', to: 'purchase#index'
      get 'done/:id(.:format)', to: 'purchase#done'
    end
    member do
      post 'pay', to: 'purchase#pay'
    end
  end
 
  resources :signups do
    collection do
      get :registration
      post :registration
      get :phone
      get :address
      get :credit
      get :done
    end
  end
  
  resources :users
  resources :category do
  end  
end

app/helpers/toppage_helper.rb
module ToppageHelper
end

app/views/shared/top_page/_asaide.html.haml
.asaide
  .inner
    %h2.inner__title スマホでかんたんフリマアプリ
    %p.inner__text 今すぐ無料ダウンロード！
    .inner__icon
      = image_tag"logo_red.svg" ,class: "mercari"
      = link_to 'https://www.apple.com/jp/ios/app-store/' do
        = image_tag("https://web-jp-assets.mercdn.net/_next/static/images/app-store-a5c17948c6fd6d5b60b13d421cd60b35.svg",class: "storeIcon store")
      = link_to 'https://play.google.com/store/apps/details?id=com.kouzoh.mercari&hl=ja' do
        = image_tag("https://web-jp-assets.mercdn.net/_next/static/images/google-play-495575abb895b405aa6336b2a4304958.svg", class: "storeIcon store")
    = image_tag"https://web-jp-assets.mercdn.net/_next/static/images/download_app_pc-a4418175e8be071827ac88d073f40e4a.png", class: "BgPhoneIcon"

app/views/shared/top_page/_footer.html.haml
.footer
  .footer-clearfix
    .about-mercari
      %h2.about-mercari__title
        メルカリについて
      %ul.about-mercari__detail
        %li
          = link_to '会社概要（運営会社）', root_path
        %li
          = link_to '採用情報', root_path
        %li
          = link_to 'プレスリリース', root_path
        %li
          = link_to '公式ブログ', root_path
        %li
          = link_to 'メリカリロゴ利用ガイドライン', root_path
        .about-mercari__link
          .about-mercari__link__twitter
            = link_to do
              = fa_icon 'twitter', class: "sns-link-icon"
          .about-mercari__link__facebook
            = link_to do
              = fa_icon 'facebook-square', class: "sns-link-icon"
    .help-and-guide
      %h2.help-and-guide__title
        ヘルプ＆ガイド
      %ul.help-and-guide__detail
        %li
          = link_to 'メルカリガイド', root_path
        %li
          = link_to 'らくらくメルカリ便', root_path
        %li
          = link_to 'ゆうゆうメルカリ便', root_path
        %li
          = link_to '大型メルカリ便', root_path
        %li
          = link_to '車体取引ガイド', root_path
        %li
          = link_to 'メルカリあんしん・あんぜん宣言！', root_path
        %li
          = link_to '偽ブランド品撲滅への取り組み', root_path
        %li
          = link_to 'メルカリボックス', root_path
    .privacy-and-rule
      %h2.privacy-and-rule__title
        プライバシーと利用規約
      .privacy-and-rule__contents
        %ul.privacy-and-rule__contents__detail
          %li
            = link_to 'プライバシーポリシー', root_path
          %li
            = link_to 'メルカリ利用規約', root_path
          %li
            = link_to 'あんしんスマホサポート制度に関する利用特約', root_path
          %li          
            = link_to 'コンプライアンスポリシー', root_path
        %ul.privacy-and-rule__contents__detail--padding
          %li
            = link_to '個人データの安全管理に係る基本方針', root_path
          %li
            = link_to '特定商取引に関する表記', root_path
          %li
            = link_to '資金決済法に基づく表示', root_path
          %li          
            = link_to '法令遵守と犯罪抑止のために', root_path
    .country
      %h2.country__title
        国
      %ul.country__detail
        %li
          = link_to '日本', root_path
        %li
          = link_to 'United States', root_path
  .footer-bottom
    %h2.footer-bottom__mercari
      = link_to '' ,root_path
    %h2.footer-bottom__copy-light
      © 2019 Mercari

app/views/shared/top_page/_header.html.haml
.header
  .header-inner
    .header-inner__top
      .header-inner__top.logo
        = link_to root_path, data: {"turbolinks" => false}do
          = image_tag 'fmarket_logo_red.svg' ,size: "170x50"
      .header-inner__top.search
        = search_form_for(@q, url: search_items_path, class: 'header-inner__top-search form') do |f|
          - if defined? words
            = f.search_field :name_or_description_cont, class: 'header-inner__top-search text', placeholder: "何かお探しですか?", value: words
          - else
            = f.search_field :name_or_description_cont, class: 'header-inner__top-search text', placeholder: "何かお探しですか?"
          = f.submit 'Search', class: 'header-inner__top-search submit'
          = button_tag type:"submit", class: 'header-inner__top-search submit' do
            %i.fa.fa-search.fa-i
    .header-inner__bottom
      %ul.search-menu
        %li.search-menu__list
          .search-menu__list__initial
            .category-js{id: "hover-click"}
              = link_to category_index_path, data: {"turbolinks" => false} do
                %i.fa.fa-list
                カテゴリーを探す
                = render "items/window"
        %li.search-menu__list
          .search-menu__list__initial
            .brand_js
              = link_to root_path, data: {"turbolinks" => false} do
                %i.fa.fa-tag.fa-lg
                ブランドから探す
                = render "items/brand"
      %ul.user-information
        - if user_signed_in?
          %li.user-information__list-login
            = link_to root_path, data: {"turbolinks" => false} do
              %i.fa.fa-heart-o.fa-lg
              %span.list-name いいね！一覧
          %li.user-information__list-login
            = link_to root_path, data: {"turbolinks" => false} do
              %i.fa.fa-bell-o.fa-lg
              %span.list-name お知らせ
          %li.user-information__list-login
            = link_to root_path, data: {"turbolinks" => false} do
              %i.fa.fa-check.fa-lg
              %span.list-name やることリスト
          %li.user-information__list-login
            = link_to "/mypages", data: {"turbolinks" => false}  do
              = image_tag asset_path('avator.jpg'), class: "avater-image", size: "30x30"
              %span.list-name-mypage マイページ  
        - else
          %li.user-information__list-nologin
            = link_to new_user_registration_path, class: "list-name-red" do
              新規会員登録
          %li.user-information__list-nologin
            = link_to new_user_session_path, class: "list-name-blue" do
              ログイン

app/views/shared/top_page/_main.html.haml
= render "shared/top_page/header"
= render "shared/top_page/sel_button"

.campaignBanner
  .main
    .mainVisual
      .content
        %h2.content__subtitle
          スマホでかんたん
          %br
          フリマアプリ
        %p.content__text
          メルカリはスマホカメラからすぐに出品できる
          %br
          購入時も安心な独自システムのアプリです
        .content__btn
          = link_to image_tag("https://web-jp-assets.mercdn.net/_next/static/images/app-store-a5c17948c6fd6d5b60b13d421cd60b35.svg", size: "170x50"), "https://itunes.apple.com/jp/app/id667861049?l=ja&mt=8", class: "aBtn"
          = link_to image_tag("https://web-jp-assets.mercdn.net/_next/static/images/google-play-495575abb895b405aa6336b2a4304958.svg", size: "170x50"), "https://play.google.com/store/apps/details?id=com.kouzoh.mercari&hl=ja", class: "gBtn"
      .picture
        = image_tag"top-banner-main-device.png", size: "440x390"
.popularCategory
  .category
    %h2.category__title 
      人気のカテゴリー
    .category__detail
      %ul.category-menu
        %li.category-menu__list
          =link_to "#", class: "category-menu__list__item" do
            レディース
        %li.category-menu__list
          =link_to "#", class: "category-menu__list__item" do
            メンズ
        %li.category-menu__list
          =link_to "#", class: "category-menu__list__item" do
            家電・スマホ・カメラ
        %li.category-menu__list
          =link_to "#", class: "category-menu__list__item" do
            おもちゃ・ホビー・グッズ 

.main-box
  .main-box__category
    .main-box__category__bar
      .main-box__category__bar__title
        とりあえず全部
      .main-box__category__bar__link      
        =link_to "#", class: "more-detail-link" do
          もっと見る
          %i.fa.fa-chevron-right

    .main-box__category__content
      .main-box__category__content__grid
        =link_to "" do
          .box
            .price ¥５
            =image_tag "https://static.mercdn.net/thumb/photos/m39106015049_1.jpg?1558957377", class: "image-box"
            .title-text hogehogehogehogehogehogehoge
        =link_to "#" do
          .box
            .price ¥215,000
            =image_tag "https://static.mercdn.net/thumb/photos/m45439819158_1.jpg?1558957377", class: "image-box"
            .title-text hogehogehogehogehogehogehoge
        =link_to "#" do
          .box
            .price ¥５
            =image_tag "https://static.mercdn.net/thumb/photos/m39106015049_1.jpg?1558957377", class: "image-box"
            .title-text hogehogehogehogehogehogehoge
        

= render "shared/top_page/asaide"
= render "shared/top_page/footer"

app/views/shared/top_page/_sel_button.html.haml
= link_to new_item_path do
  .sell-btn
    .sell-btn__title 出品
    = fa_icon 'camera',class:'camera-icon'