config/routes.rb
Rails.application.routes.draw do
  
  get 'purchase/index'
  get 'purchase/done'
  get 'credit_cards/new'
  get 'credit_cards/show'
  post   '/like/:item_id' => 'likes#like',   as: 'like'
  delete '/like/:item_id' => 'likes#unlike', as: 'unlike'
  

  devise_for :users

    devise_scope :user do
      get 'uses/before_sign_up' => 'devise/registrations#before_signup', as: :before_signup_user_registration
      post 'uses/before_sign_up(.:format)' => 'devise/registrations#before_signup'
      post 'users/sign_up' => 'users/registrations#new'
      get 'users/new2' => 'devise/registrations#new2', as: :new2_user_registration
      post 'users/new2(.:format)' => 'devise/registrations#new2'
      get 'users/new3' => 'devise/registrations#new3', as: :new3_user_registration
      post 'users/new3(.:format)' => 'devise/registrations#new3'
      get 'users/new4' => 'devise/registrations#new4', as: :new4_user_registration
      post 'users/new4(.:format)' => 'devise/registrations#new4'
      get 'users/new5' => 'devise/registrations#new5', as: :new5_user_registration
      post 'users/new5(.:format)' => 'devise/registrations#new5'      
    end

  root to: 'items#index'
  get 'mypages' => 'mypages#index'
  get 'itemsshow' => 'items#show'
  get 'users/logout' => 'users#logout'
  get 'users/credit' => 'users#credit'
  get 'itemscheck' => 'items#check'
  get 'itemsindex' => 'items#index'
  

  resources :mypages, only: [:index,:edit]do
    collection do
      get "credit", to: "mypages#credit"
      get "logout", to: "mypages#logout"
      get "profile", to: "mypages#profile"
      get "identification", to: "mypages#identification"
      get "myitem", to: "mypages#myitem"
    end
    member do
      get 'item', to: 'mypages#item'
      post 'stop', to: 'mypages#stop'
      post 'start', to: 'mypages#start'
    end
    
  end

  resources :items, only: [:index, :show, :new, :destroy, :edit, :create] do
    collection do
      get "check/:id(.:format)", to: "items#check"
      get 'child_category'
      get 'grandchild_category'
      get 'size'
      get 'search'
    end
  end

  resources :credit_cards, only: [:new, :show] do
    collection do
      post  'new', to: 'credit_cards#new'
      post 'show', to: 'credit_cards#show'
      post 'pay', to: 'credit_cards#pay'
    end
  end
  resources :purchase, only: [:index] do
    collection do
      get 'index', to: 'purchase#index'
      get 'done/:id(.:format)', to: 'purchase#done'
    end
    member do
      post 'pay', to: 'purchase#pay'
    end
  end
 
  resources :signups do
    collection do
      get :registration
      post :registration
      get :phone
      get :address
      get :credit
      get :done
    end
  end
  
  resources :users
  resources :category do
  end  
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  
  before_action :set_variables

  def like
    like = current_user.likes.new(item_id: @item.id)
    like.save
  end

  def unlike
    like = current_user.likes.find_by(item_id: @item.id)
    like.destroy
  end

  private

  def set_variables
    @item = Item.find(params[:item_id])
    @id_name = "#like-link-#{@item.id}"
    @id_heart = "#heart-#{@item.id}"
  end
end

app/views/likes/_like_links.html.haml
%div.like-link{id: "like-link-#{item.id}"}
  - if user_signed_in?
    - if current_user.likes.find_by(item_id: item.id)
      = link_to unlike_path(item.id), method: :delete, remote: true do
        %i.fa.fa-heart{id: "heart-#{item.id}"}
        いいね!
        = item.likes.count.to_s
    - else
      = link_to like_path(item.id), method: :post, remote: true do
        %i.fa.fa-heart-o{id: "heart-#{item.id}"}
        いいね!
        = item.likes.count.to_s
  -else
    = link_to new_user_session_path do
      %i.fa.fa-heart-o{id: "heart-#{item.id}"}
      いいね!
      = item.likes.count.to_s

app/views/likes/like.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like_links", item: @item  )) %>');
$("<%= @id_heart %>").removeClass('fa-heart-o').addClass('fa-heart');

app/views/likes/unlike.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render("likes/like_links", item: @item  )) %>');
$("<%= @id_heart %>").removeClass('fa-heart').addClass('fa-heart-o');