config/routes.rb
Rails.application.routes.draw do
  
  get 'purchase/index'
  get 'purchase/done'
  get 'credit_cards/new'
  get 'credit_cards/show'
  post   '/like/:item_id' => 'likes#like',   as: 'like'
  delete '/like/:item_id' => 'likes#unlike', as: 'unlike'
  

  devise_for :users

    devise_scope :user do
      get 'uses/before_sign_up' => 'devise/registrations#before_signup', as: :before_signup_user_registration
      post 'uses/before_sign_up(.:format)' => 'devise/registrations#before_signup'
      post 'users/sign_up' => 'users/registrations#new'
      get 'users/new2' => 'devise/registrations#new2', as: :new2_user_registration
      post 'users/new2(.:format)' => 'devise/registrations#new2'
      get 'users/new3' => 'devise/registrations#new3', as: :new3_user_registration
      post 'users/new3(.:format)' => 'devise/registrations#new3'
      get 'users/new4' => 'devise/registrations#new4', as: :new4_user_registration
      post 'users/new4(.:format)' => 'devise/registrations#new4'
      get 'users/new5' => 'devise/registrations#new5', as: :new5_user_registration
      post 'users/new5(.:format)' => 'devise/registrations#new5'      
    end

  root to: 'items#index'
  get 'mypages' => 'mypages#index'
  get 'itemsshow' => 'items#show'
  get 'users/logout' => 'users#logout'
  get 'users/credit' => 'users#credit'
  get 'itemscheck' => 'items#check'
  get 'itemsindex' => 'items#index'
  

  resources :mypages, only: [:index,:edit]do
    collection do
      get "credit", to: "mypages#credit"
      get "logout", to: "mypages#logout"
      get "profile", to: "mypages#profile"
      get "identification", to: "mypages#identification"
      get "myitem", to: "mypages#myitem"
    end
    member do
      get 'item', to: 'mypages#item'
      post 'stop', to: 'mypages#stop'
      post 'start', to: 'mypages#start'
    end
    
  end

  resources :items, only: [:index, :show, :new, :destroy, :edit, :create] do
    collection do
      get "check/:id(.:format)", to: "items#check"
      get 'child_category'
      get 'grandchild_category'
      get 'size'
      get 'search'
    end
  end

  resources :credit_cards, only: [:new, :show] do
    collection do
      post  'new', to: 'credit_cards#new'
      post 'show', to: 'credit_cards#show'
      post 'pay', to: 'credit_cards#pay'
    end
  end
  resources :purchase, only: [:index] do
    collection do
      get 'index', to: 'purchase#index'
      get 'done/:id(.:format)', to: 'purchase#done'
    end
    member do
      post 'pay', to: 'purchase#pay'
    end
  end
 
  resources :signups do
    collection do
      get :registration
      post :registration
      get :phone
      get :address
      get :credit
      get :done
    end
  end
  
  resources :users
  resources :category do
  end  
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
 
  belongs_to :user
  belongs_to :category
  belongs_to :brand
  has_many :item_images, dependent: :destroy
  accepts_nested_attributes_for :item_images

  has_many :likes, dependent: :destroy
  def like_by?(user) #いいねしているかどうか
    likes.where(user_id: user.id).exists?
  end

  has_one :buyer, dependent: :destroy
  
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :condition
  belongs_to_active_hash :postage
  belongs_to_active_hash :shipping_date
  belongs_to_active_hash :shipping_method
  belongs_to_active_hash :size

  # バリデーション
  validates :name, length: { in: 1..40 }
  validates :description, length: { in: 1..1000 }
  validates :category_id, numericality: {message: 'を選択してください'}
  validates :size_id, numericality: {message: 'を選択してください'}, allow_nil: true
  validates :status, presence: {
    if: proc { |d| d.status == nil },
    message: 'を選択してください' 
  }
  validates :postage_id, exclusion: {in: %w(---), message: 'を選択してください'}
  validates :prefecture_id, exclusion: {in: %w(---), message: 'を選択してください'}
  validates :shipping_date_id, exclusion: {in: %w(---), message: 'を選択してください'}
  validates :price,  numericality: {only_integer: true,
                                    greater_than_or_equal_to: 300,
                                    less_than_or_equal_to: 9999999,
                                    message: 'は300以上9999999以下で入力してください' }
                                    
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController 
  before_action :authenticate_user!, only: [:sell, :create, :edit, :update, :destroy, :buy]
  before_action :set_item, only: [:show, :edit]
  before_action :set_search
  before_action :move_to_sign_up, except: [:index, :show,:child_category,:grandchild_category]

  def index
    @items = Item.limit(50)
    @category_lady = Item.where(category_id: 1..199)
    @category_man = Item.where(category_id: 200..344)
    @category_electrical_appliances = Item.where(category_id: 893..978)
    @category_toy = Item.where(category_id: 680..792)

  end


  def show
    @items = Item.all
    @item_images = ItemImage.all
    @other_items = Item.where( [ "id != ? and user_id = ?", params[:id], @item.user_id ] ).order("created_at DESC").limit(6)
    @same_items = Item.where( [ "id != ? and user_id != ?", params[:id], @item.user_id ] ).where(brand_id: @item.brand_id ).order("created_at DESC").limit(6)
   
  end


  def destroy
    item = Item.find(params[:id])
    if item.user_id == current_user.id
     item.destroy
     flash[:alert] = '商品を削除しました'
     redirect_to mypages_path
    else
    
    flash[:alert] = '削除出来ませんでした'
    redirect_to action: 'edit' 
    end
  end

  def edit
  end

  def check
    @item = Item.find(params[:id])
  end

  def new

    @item= Item.new
    @parents = Category.where(ancestry: nil) 
    @item.item_images.build

  end

  def create
    # カテゴリーIDの値の設定
    category = ""    
    if item_params[:third_category_id].blank?
      if item_params[:second_category_id].blank? 
        category = item_params[:category_id]
      else
        category = item_params[:second_category_id]
      end
    else
      category = item_params[:third_category_id]
    end

    @brand= Brand.new(
      name: item_params[:brand_id]
    )

    # ブランドIDの値の設定
    if @brand.name.blank?
      @brand.id = 1
    else
      # ID:1 は未入力
      @brand.save
    end

      # ブランドIDの値の設定
      size=""
      if item_params[:size_id].blank?
        size=0

      else
        # ID:1 は未入力
        size=item_params[:size_id]
      end

    @item = Item.new(
      name: item_params[:name],
      description: item_params[:description],
      category_id: category,
      size_id: size,
      condition_id: item_params[:condition_id],
      postage_id: item_params[:postage_id],
      prefecture_id: item_params[:prefecture_id],
      shipping_date_id: item_params[:shipping_date_id],
      shipping_method_id: item_params[:shipping_method_id],
      price: item_params[:price],
      brand_id: @brand.id,
      user_id: current_user.id,
      status: 0
    )

    # @item.item_images.build(
    #   image:item_params[:image]
    # )

    if @item.save
      # 商品詳細ページへ遷移 
      params[:image]['image'].each do |image|
        @item.item_images.create(image: image, item_id: @item.id)
      end
      
      redirect_to @item, notice: '出品が完了しました'
    else
      redirect_to root_path, notice: '出品に失敗しました。'
    end

  end

  def brand
    @items = Item.limit(50)
    
  end

  def child_category
    @children = Category.where(ancestry: params[:parent_id])
    respond_to do |format|
      format.html
      format.json
    end
  end
  
  def grandchild_category
    @grandchildren = Category.where(ancestry: "#{params[:parent_id]}/#{params[:child_id]}")
    respond_to do |format|
      format.html
      format.json
    end
  end

  def size
    @size = Size.all
    respond_to do |format|
      format.html
      format.json
    end
  end

  def search
    @search_words = params[:q][:name_or_description_cont] unless !params[:q].present? || @search_words.present?
    @words = params[:q].delete(:name_or_description_cont) if params[:q].present?
    if @words.present?
      params[:q][:groupings] = []
      @words.split(/[ 　]/).each_with_index do |word, i| #全角空白と半角空白で切って、単語ごとに処理します
        params[:q][:groupings][i] = { name_or_description_cont: word }
      end
    end
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end
  
  def item_params
    params.require(:item).permit(
    :name, 
    :description, 
    :category_id, 
    :second_category_id,
    :third_category_id,
    :size_id, 
    :brand_id,
    :condition_id,
    :postage_id,
    :prefecture_id, 
    :shipping_date_id,
    :shipping_method_id,
    :price,
    :image,
    [image: [:image]]
    ).merge(user_id: current_user.id)
  end
  
  def search_params
    params.require(:q).permit(:name_and_description_cont_any)
  end

  def set_search
    @q = Item.ransack(params[:q])
    @items = @q.result(distinct: true)
  end

  def move_to_sign_up
    redirect_to new_user_session_path unless user_signed_in?
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_brand.html.haml
.brand_list
  .brands_list
    = link_to "シャネル", root_path, class: "brand_category",id: "100001"
    = link_to "ナイキ", root_path, class: "brand_category",id: "100002"
    = link_to "ルイ　ヴィトン", root_path, class: "brand_category",id: "100003"
    = link_to "アディダス", root_path, class: "brand_category",id: "100004"
    = link_to "ブランド一覧", root_path, class: "brand_category",id: "100005"

app/views/items/_items.html.haml
= render 'likes/like_links', item: @item

app/views/items/_main.html.haml
.main-box
  .main-box__category
    .main-box__category__bar
      .main-box__category__bar__title
        = @parents[0].name + "新着アイテム"
      .main-box__category__bar__link
        =link_to category_path(@parents[0].id), class: "more-detail-link" ,id: @parents[0].id do
          もっと見る
          %i.fa.fa-chevron-right
    .main-box__category__content
      .main-box__category__content__grid
        - @category_lady.each do |i|
          =link_to "/items/#{i.id}" do
            .box
              .price 
                ¥
                =i.price.to_s(:delimited, delimiter: ',')
              - if i.status == 3
                .sold-logo
              - elsif i.status == 2
                .stopping-logo
              =image_tag i.item_images[0].image.url, alt: 'next', class:'image-box'
              .title-text
                =i.name
.main-box
  .main-box__category
    .main-box__category__bar
      .main-box__category__bar__title
        = @parents[1].name + "新着アイテム"
      .main-box__category__bar__link
        =link_to category_path(@parents[1].id), class: "more-detail-link" do
          もっと見る
          %i.fa.fa-chevron-right
    .main-box__category__content
      .main-box__category__content__grid
        - @category_man.each do |i|
          =link_to "/items/#{i.id}" do
            .box
              .price 
                ¥
                =i.price.to_s(:delimited, delimiter: ',')
              - if i.status == 3
                .sold-logo
              - elsif i.status == 2
                .stopping-logo
              =image_tag i.item_images[0].image.url, alt: 'next', class:'image-box'
              .title-text
                =i.name

.main-box
  .main-box__category
    .main-box__category__bar
      .main-box__category__bar__title
        = @parents[7].name + "新着アイテム"
      .main-box__category__bar__link
        =link_to category_path(@parents[7].id), class: "more-detail-link" do
          もっと見る
          %i.fa.fa-chevron-right
    .main-box__category__content
      .main-box__category__content__grid
        - @category_electrical_appliances.each do |i|
          =link_to "/items/#{i.id}" do
            .box
              .price 
                ¥
                =i.price.to_s(:delimited, delimiter: ',')
              - if i.status == 3
                .sold-logo
              - elsif i.status == 2
                .stopping-logo
              =image_tag i.item_images[0].image.url, alt: 'next', class:'image-box'
              .title-text
                =i.name
.main-box
  .main-box__category
    .main-box__category__bar
      .main-box__category__bar__title
        = @parents[5].name + "新着アイテム"
      .main-box__category__bar__link
        =link_to category_path(@parents[5].id), class: "more-detail-link" do
          もっと見る
          %i.fa.fa-chevron-right
    .main-box__category__content
      .main-box__category__content__grid
        - @category_toy.each do |i|
          =link_to "/items/#{i.id}" do
            .box
              .price 
                ¥
                =i.price.to_s(:delimited, delimiter: ',')
              - if i.status == 3
                .sold-logo
              - elsif i.status == 2
                .stopping-logo
              =image_tag i.item_images[0].image.url, alt: 'next', class:'image-box'
              .title-text
                =i.name

app/views/items/_window.html.haml
.category_list
  .parents_list
    - @parents.each do |parent|
      = link_to "#{parent.name}", category_path(parent), class: "parent_category",id: "#{parent.id}"
  .children_list
  .grand_children_list

app/views/items/edit.html.haml
= render "shared/top_page/header"
.fieldspace
.item-box
  .item-title
    %h2 商品名
  .item-messeage
    %h2 商品名
  .item-inline-box
    .item-photos
      .item-photos__sub-img
        - @item.item_images.each_with_index do |img,i|
          = image_tag @item.item_images[i].image.url ,size: "60x60" ,class: "item-photos__sub-img__sub"
    .item-center-space
    .item-detail-table
      %table.item-detail-table__detail-table
        %tbody.item-detail-table__detail-table__tbody
          %tr.item-detail-table__detail-table__tbody__tr
            %th.item-detail-table__detail-table__tbody__th
              出品者
            %td.item-detail-table__detail-table__tbody__td
              出品者のID名
              .item-detail-table__detail-table__tbody__td__rating
                .item-detail-table__detail-table__tbody__td__icon
                  = fa_icon "google", class: "good-icon"
                  %span.item-detail-table__detail-table__tbody__td__icon__num
                    100
                .item-detail-table__detail-table__tbody__td__icon
                  = fa_icon  "google", class: "normal-icon"
                  %span.item-detail-table__detail-table__tbody__td__icon__num
                    50
                .item-detail-table__detail-table__tbody__td__icon
                  = fa_icon  "google", class: "bad-icon"
                  %span.item-detail-table__detail-table__tbody__td__icon__num
                    10
          %tr.item-detail-table__detail-table__tbody__tr
            %th.item-detail-table__detail-table__tbody__th
              カテゴリー
            %td.item-detail-table__detail-table__tbody__td
              %span.item-category
                カテゴリー
          %tr.item-detail-table__detail-table__tbody__tr
            %th.item-detail-table__detail-table__tbody__th
              ブランド
            %td.item-detail-table__detail-table__tbody__td
              = link_to "ブランド名", root_path, method: :get, class: "brand-name link"
          %tr.item-detail-table__detail-table__tbody__tr
            %th.item-detail-table__detail-table__tbody__th
              商品のサイズ
            %td.item-detail-table__detail-table__tbody__td
              %span.item-size
                XS
          %tr.item-detail-table__detail-table__tbody__tr
            %th.item-detail-table__detail-table__tbody__th
              商品の状態
            %td.item-detail-table__detail-table__tbody__td
              %span.item-condition
                美品
          %tr.item-detail-table__detail-table__tbody__tr
            %th.item-detail-table__detail-table__tbody__th
              配送料の負担
            %td.item-detail-table__detail-table__tbody__td
              %span.shipping-charge
                落札者が負担
          %tr.item-detail-table__detail-table__tbody__tr
            %th.item-detail-table__detail-table__tbody__th
              配送の方法
            %td.item-detail-table__detail-table__tbody__td
              %span.shipping-method
                佐川郵便
          %tr.item-detail-table__detail-table__tbody__tr
            %th.item-detail-table__detail-table__tbody__th
              配送元地域
            %td.item-detail-table__detail-table__tbody__td
              = link_to "配送地域", root_path, method: :get, class: "prefecture link"
          %tr.item-detail-table__detail-table__tbody__tr
            %th.item-detail-table__detail-table__tbody__th
              発送日の目安
            %td.item-detail-table__detail-table__tbody__td
              %span.shipping-date
                1日から2日
  .item-price-box
    .item-price-box__box
      %span.item-price-box__box--price
        ¥1,000
      %span.item-price-box__box--tax
        （税込）
      %span.item-price-box__box--shipping-charge
        送料込み
  / 説明文
  .item-explain__description
    %p.item-explain__description-inner
      商品の紹介商品の紹介商品の紹介商品の紹介商品の紹介商品の紹介商品の紹介商品の紹介商品の紹介商品の紹介商品の紹介商品の紹介商品の紹介商品の紹介
      商品の紹介商品の紹介商品の紹介商品の紹介商品の紹介商品の紹介商品の紹介商品の紹介商品の紹介商品の紹介商品の紹介商品の紹介
      商品の紹介商品の紹介商品の紹介商品の紹介商品の紹介商品の紹介商品の紹介商品の紹介商品の紹介商品の紹介商品の紹介
    
      / 商品へのコメント
  .item-space-box1
    /btn-box
  .item-space-box2
  .item-btn-box
    = button_to "商品の編集", root_path, class: "item-btn-box__btn item-btn-box__btn--red"
    .item-btn-box__text　or
    = button_to "この商品を削除する", item_path(7), method: :delete, class: "item-btn-box__btn item-btn-box__btn--gray" 
  .item-space-box2

  .item-comment-box
    .item-space-box1
    .item-comment-box__form__text
      相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
    .item-space-box1
    .item-comment-box__form__textarea
    .item-space-box1
  = button_to "コメントする", root_path, class: "comment-btn btn-gray"
  .item-space-box1
  .item-space-box1
  / 前後ページリンク

  %ul.item-page-link
    %li.item-page-link__prev
      = link_to root_path, class: "link" do
        = fa_icon "angle-left"
        %span
          前　似たような商品
    %li.item-page-link__next
      = link_to root_path, class: "link" do
        %span
          後ろ　似たような商品
        = fa_icon "angle-right"      
  .item-sns
    %ul.item-sns__list
      %li.item-sns__list__icon
        = link_to root_path class: "link social-link" do
          = fa_icon "facebook-square", class: "item-sns__list__icon--facebook"
      %li.item-sns__list__icon
        = link_to root_path, class: "link social-link" do
          = fa_icon "twitter-square", class: "item-sns__list__icon--twitter"
      %li.item-sns__list__icon
        = link_to root_path, class: "link social-link" do
          = fa_icon "pinterest-square", class: "item-sns__list__icon--pinterest"
  .item-space-box2
  .item-space-box2
  .item-space-box2
  .item-space-box2

app/views/items/show.html.haml
= render "shared/top_page/header"
.fieldspace
.item-box
  .item-title
    %h2= @item.name
  .item-messeage
    
  .item-inline-box
    .item-photos
      .item-photos__main-img
        - if @item.status == 3
          .sold-logo
        - elsif @item.status == 2
          .stopping-logo
        = image_tag @item.item_images[0].image.url ,size: "300x300" 
      .item-photos__sub-img
        - @item.item_images.each_with_index do |img,i|
          = image_tag @item.item_images[i].image.url ,size: "60x60" ,class: "item-photos__sub-img__sub"
    .item-center-space
    .item-detail-table
      %table.item-detail-table__detail-table
        %tbody.item-detail-table__detail-table__tbody
          %tr.item-detail-table__detail-table__tbody__tr
            %th.item-detail-table__detail-table__tbody__th
              出品者
            %td.item-detail-table__detail-table__tbody__td
              = @item.user.nickname
              .item-detail-table__detail-table__tbody__td__rating
                .item-detail-table__detail-table__tbody__td__icon
                  = fa_icon "google", class: "good-icon"
                  %span.item-detail-table__detail-table__tbody__td__icon__num
                    = @item.user.user_evaluation.good
                .item-detail-table__detail-table__tbody__td__icon
                  = fa_icon  "google", class: "normal-icon"
                  %span.item-detail-table__detail-table__tbody__td__icon__num
                    = @item.user.user_evaluation.normal
                .item-detail-table__detail-table__tbody__td__icon
                  = fa_icon  "google", class: "bad-icon"
                  %span.item-detail-table__detail-table__tbody__td__icon__num
                    = @item.user.user_evaluation.bad
          %tr.item-detail-table__detail-table__tbody__tr
            %th.item-detail-table__detail-table__tbody__th
              カテゴリー
            %td.item-detail-table__detail-table__tbody__td
              %span.item-category
                = @item.category.parent.parent.name
                %br/
                = @item.category.parent.name
                %br/
                = @item.category.name
                
          %tr.item-detail-table__detail-table__tbody__tr
            %th.item-detail-table__detail-table__tbody__th
              ブランド
            %td.item-detail-table__detail-table__tbody__td
              = link_to @item.brand.name, root_path, method: :get, class: "brand-name link"
          %tr.item-detail-table__detail-table__tbody__tr
            %th.item-detail-table__detail-table__tbody__th
              商品のサイズ
            %td.item-detail-table__detail-table__tbody__td
              %span.item-size
                = @item.size.name
          %tr.item-detail-table__detail-table__tbody__tr
            %th.item-detail-table__detail-table__tbody__th
              商品の状態
            %td.item-detail-table__detail-table__tbody__td
              %span.item-condition
                =@item.condition.name
          %tr.item-detail-table__detail-table__tbody__tr
            %th.item-detail-table__detail-table__tbody__th
              配送料の負担
            %td.item-detail-table__detail-table__tbody__td
              %span.shipping-charge
                = @item.postage.name
          %tr.item-detail-table__detail-table__tbody__tr
            %th.item-detail-table__detail-table__tbody__th
              配送の方法
            %td.item-detail-table__detail-table__tbody__td
              %span.shipping-method
                = @item.shipping_method.name
          %tr.item-detail-table__detail-table__tbody__tr
            %th.item-detail-table__detail-table__tbody__th
              配送元地域
            %td.item-detail-table__detail-table__tbody__td
              = link_to "配送地域", root_path, method: :get, class: "prefecture link"
              =@item.prefecture.name
          %tr.item-detail-table__detail-table__tbody__tr
            %th.item-detail-table__detail-table__tbody__th
              発送日の目安
            %td.item-detail-table__detail-table__tbody__td
              %span.shipping-date
                =@item.shipping_date.name
  .item-price-box
    .item-price-box__box
      %span.item-price-box__box--price
        ¥
        =@item.price
      %span.item-price-box__box--tax
        （税込）
      %span.item-price-box__box--shipping-charge
        送料込み
  - if @item.status == 3
    .buy-btn.btn-gray
      売り切れました
  - else
    = link_to "購入画面に進む", "/items/check/#{@item.id}", class: "buy-btn btn-red"
  / 説明文
  .item-explain__description
    %p.item-explain__description-inner
      = simple_format(@item.description)
    / いいねボタン、不適切ボタン
    .item-explain__item-btn
      .item-explain__item-btn__left
        .item-explain__item-btn__left__like-btn
          = render partial: 'items/items'
        .item-explain__item-btn__left__report
          = link_to root_path, method: :get, class: "link" do
            = fa_icon "flag", class: "item-explain__item-btn__left__report__icon"
            %span.item-explain__item-btn__left__report__text
              不適切な商品の報告
      .item-explain__item-btn__right
        = link_to root_path, method: :get, class: "item-explain__item-btn__right__icon link" do
          = fa_icon "flock"
          %span.item-explain__item-btn__right__text
            あんしん・あんぜんへの取り組み
      / 商品へのコメント
  .item-space-box1
  .item-space-box2
  .item-comment-box
    .item-space-box1
    .item-comment-box__form__text
      相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
    .item-space-box1
    .item-comment-box__form__textarea
      %input{type: "textarea", class: "input-box-form"}
    .item-space-box1
  = button_to "コメントする", root_path, class: "comment-btn btn-gray"
  .item-space-box1
  .item-space-box1
  / 前後ページリンク

  %ul.item-page-link
    %li.item-page-link__prev
      = link_to root_path, class: "link" do
        = fa_icon "angle-left"
        %span
          前　似たような商品
    %li.item-page-link__next
      = link_to root_path, class: "link" do
        %span
          後ろ　似たような商品
        = fa_icon "angle-right"      
  .item-sns
    %ul.item-sns__list
      %li.item-sns__list__icon
        = link_to root_path class: "link social-link" do
          = fa_icon "facebook-square", class: "item-sns__list__icon--facebook"
      %li.item-sns__list__icon
        = link_to root_path, class: "link social-link" do
          = fa_icon "twitter-square", class: "item-sns__list__icon--twitter"
      %li.item-sns__list__icon
        = link_to root_path, class: "link social-link" do
          = fa_icon "pinterest-square", class: "item-sns__list__icon--pinterest"

  .item-space-box2
  .item-space-box2
  .item-space-box2
  .item-space-box2
  .item-other
    %section.item-other__user-items
      %h2.item-other__user-items__head
        = link_to @item.user.nickname+"さん　その他の商品", root_path, class: "link item-link"
      .item-other__user-items__content
        - @other_items.each do |other_item|
          %section.item-other__user-items__content__box
            = link_to  item_path(other_item.id), class: "linkblack item-link" do
              .item-other__user-items__content__box__photo
                - if other_item.status == 3
                  .sold-logo
                - elsif other_item.status == 2
                  .stopping-logo
                %h3.item-other__user-items__content__box__itemname__name
                  = other_item.name
                .item-other__user-items__content__box__itemname__num
                  .item-other__user-items__content__box__itemname__num__price
                    ¥
                    = other_item.price
                  .item-other__user-items__content__box__itemname__num__likes
                    = fa_icon "heart", class: "like-icon"
                    %span.item-other__user-items__content__box__itemname__num__likes__num
                      5
  .item-space-box2
  .item-space-box2
  .item-space-box2
  .item-space-box2
  .item-other
    %section.item-other__user-items
      %h2.item-other__user-items__head
        = link_to "#{@item.brand.name}(同じカテゴリ) その他の商品", root_path, class: "link item-link"
      .item-other__user-items__content
        - @same_items.each do |same_item|
          %section.item-other__user-items__content__box
            = link_to  item_path(same_item.id), class: "linkblack item-link" do
              .item-other__user-items__content__box__photo
                - if same_item.status == 3
                  .sold-logo
                - elsif same_item.status == 2
                  .stopping-logo
                = image_tag same_item.item_images[0].image.url , class: "item-image"            
                %h3.item-other__user-items__content__box__itemname__name
                  = same_item.name
                .item-other__user-items__content__box__itemname__num
                  .item-other__user-items__content__box__itemname__num__price
                    ¥
                    = same_item.price
                  .item-other__user-items__content__box__itemname__num__likes
                    = fa_icon "heart", class: "like-icon"
                    %span.item-other__user-items__content__box__itemname__num__likes__num
                      7

%ul.item-bottom
  %li.item-bottom-text1
    = link_to root_path, class: "link" do
      %span
        メルカリ　
  %li.item-bottom-text2
    %span
      商品名
      = fa_icon "angle-right"                 
.fieldspace
= render "shared/top_page/asaide"
= render "shared/top_page/footer"